[package]
name = "bytecodec_derive"
version = "0.0.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
bytecodec = "0.4"
quote = "0.6"
syn = "0.15"
trackable = "0.2"
